export const patItems = [
    {
        patient_ID : '1',
        username : 'This is the Username',
        password : '123',
        patient_name: 'Ku Ming Roong',
        patient_dob: '18/10/2001',
        patient_address: 'cheras',
        // patient_history: '',
        // status: '',
    },
    {
        patient_ID : '2',
        username : 'ron',
        password : '123',
        patient_name: 'Ron',
        patient_dob: '18/10/2001',
        patient_address: 'ampang',
        // patient_history: '',
        // status: '',
    },
    {
        patient_ID : '3',
        username : 'ron',
        password : '123',
        patient_name: 'Ron',
        patient_dob: '18/10/2001',
        patient_address: 'cheras',
        // patient_history: '',
        // status: '',
    },
    {
        patient_ID : '4',
        username : 'ron',
        password : '123',
        patient_name: 'Ku',
        patient_dob: '18/10/2001',
        patient_address: 'cheras',
        // patient_history: '',
        // status: '',
    },
    {
        patient_ID : '5',
        username : 'ron',
        password : '123',
        patient_name: 'Ku Ming Roong',
        patient_dob: '18/10/2001',
        patient_address: 'ampang',
        // patient_history: '',
        // status: '',
    },
    {
        patient_ID : '6',
        username : 'ron',
        password : '123',
        patient_name: 'Ku Ming Roong',
        patient_dob: '18/10/2001',
        patient_address: 'cheras',
        // patient_history: '',
        // status: '',
    },
    {
        patient_ID : '7',
        username : 'ron',
        password : '123',
        patient_name: 'Ku Ming Roong',
        patient_dob: '18/10/2001',
        patient_address: 'cheras',
        // patient_history: '',
        // status: '',
    },
    {
        patient_ID : '8',
        username : 'ron',
        password : '123',
        patient_name: 'Ku Ming Roong',
        patient_dob: '18/10/2001',
        patient_address: 'ampang',
        // patient_history: '',
        // status: '',
    },
    {
        patient_ID : '9',
        username : 'ron',
        password : '123',
        patient_name: 'Ku Ming Roong',
        patient_dob: '18/10/2001',
        patient_address: 'cheras',
        // patient_history: '',
        // status: '',
    },
    {
        patient_ID : '10',
        username : 'ron',
        password : '123',
        patient_name: 'Ku Ming Roong',
        patient_dob: '18/10/2001',
        patient_address: 'cheras',
        // patient_history: '',
        // status: '',
    },
    {
        patient_ID : '11',
        username : 'ron',
        password : '123',
        patient_name: 'Ku Ming Roong',
        patient_dob: '18/10/2001',
        patient_address: 'ampang',
        // patient_history: '',
        // status: '',
    },
    {
        patient_ID : '12',
        username : 'ron',
        password : '123',
        patient_name: 'Ku Ming Roong',
        patient_dob: '18/10/2001',
        patient_address: 'cheras',
        // patient_history: '',
        // status: '',
    },
]